services:
  - type: web
    name: BrasilBurger
    id: srv-d50v5jali9vc73emhdag
    runtime: docker
    repo: https://github.com/yacine004/BrasilBurger
    branch: csharp
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        sync: false
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Cloudinary__CloudName
        sync: false
      - key: Cloudinary__ApiKey
        sync: false
      - key: Cloudinary__ApiSecret
        sync: false
