framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection:
    #    enabled: true
    #http_method_override: true

    # Uncomment when using the "App\Kernel" class instead of the default one
    # kernel:
    #     class: App\Kernel

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true
