when@prod:
    framework:
        logger:
            handlers:
                main:
                    type: fingers_crossed
                    action_level: error
                    handler: nested
                    excluded_http_codes: [404, 405]
                nested:
                    type: stream
                    path: "%kernel.logs_dir%/%kernel.environment%.log"
                console:
                    type: console
                    process_psr_3_messages: false
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
